# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       mer-gfx-tests
Summary:    Mer Graphics Tests
Version:    0.0.1
Release:    1
Group:      Development/Tools
License:    GPL
URL:        http://gitweb.merproject.org/gitweb?p=mer-core/mer-gfx-tests.git;a=summary
Source0:    mer-gfx-tests-0.0.1.tar.gz
Source100:  mer-gfx-tests.yaml
Patch0:     0001-Include-missing-header-and-use-native-window-type.patch
BuildRequires:  pkgconfig(egl)
BuildRequires:  pkgconfig(glesv2)


%description
Test and debug for EGL



%prep
%setup -q -n kernel

# 0001-Include-missing-header-and-use-native-window-type.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
%{_bindir}/eglinfo
%{_bindir}/glestest
# >> files
# << files


